extends Node














func _stamps(): pass
var stamps = {
	"1+ Domino in Hand" : {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>+1 <#296e8f>Hand",
						   "descripcion" : "This Stamp adds <#296e8f>+1 to your <#296e8f>Hand of Dominos",
						   },
	
	"1+ Draw" : {"size" : Vector2(16,16),
				 "position" : Vector2(16,0),
				 "plata": "<#b1911a>10",
				 "titulo" : "<#f3983a>+1 <#f3983a>Draw",
				 "descripcion" : "This Stamp adds <#296e8f>+1 to your <#f3983a>Draws of Dominos",
				},
}



# padre es 0 significa que puede ser padre o hijo, si es 1 solo puede ser hijo, si es 2 solo puede ser padre, si es 3 puede ser padre extra.
func _dominos_especiales(): pass
var dominos_especiales = {
	"Bomb" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(208, 0),
				"flechitas" : ["↖", "↗", "↘", "↙"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 0.5,
				"puntaje_siguiente": 0,
				"puntaje": 10,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(48, 192),
				"titulo": "<#238c73>Bomb",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "This domino <#e0483e>Explodes when it falls knocking over other dominos.", # ejemplo: "This domino adds <#f3983a>+1"
			},
	"50 Pointer" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(112, 0),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 50,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(80, 192),
				"titulo": "<#296e8f>50 Pointer",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "This domino Adds <#296e8f>+50 points when it falls." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"2x Behind" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(80, 0),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(16, 192),
				"titulo": "<#e0483e>2x Behind",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "This domino <#296e8f>Adds the amount made before itself <#e0483e>times <#e0483e>2." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Banana" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(144, 0),
				"flechitas" : ["→", "←"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(4800, 192),
				"titulo": "<#e19124>Banana",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "This domino Falls to the front and <#238c73>THEN to the back of itself." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Double" :  {
				"tipo" : "especial",
				"chance": 4,  # algo menos común
				"region_rect_cords": Vector2(176, 0),
				"flechitas" : ["→", "↳"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(48, 192),
				"titulo": "<#238c73>Double",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Can knock down <#296e8f>2 dominos." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Multiplier 3x" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(240, 0),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(16, 192),
				"titulo": "<#e0483e>Multiplier <#e0483e>3x",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "<#e0483e>Triples everything in the chain if this domino is the <#e0483e>3rd in the <#296e8f>row." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Specific 100" :  {
				"tipo" : "especial",
				"chance": 6,  # algo menos común
				"region_rect_cords": Vector2(272, 0),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(80, 192),
				"titulo": "Specific <#296e8f>100",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Adds <#296e8f>+100 if it’s the <#e0483e>2nd and last in a row." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Reverse" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(304, 0),
				"flechitas" : ["↺"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(48, 192),
				"titulo": "<#238c73>Reverse",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "<#238c73>Reverses the fall direction of a row of dominos." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Long Shot" :  {
				"tipo" : "especial",
				"chance": 4,  # algo menos común
				"region_rect_cords": Vector2(48, 0),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(80, 192),
				"titulo": "<#296e8f>Long Shot",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "<#296e8f>Adds to the score the number of dominos that fell because of this one." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Sniper" :  {
				"tipo" : "especial",
				"chance": 6,  # algo menos común
				"region_rect_cords": Vector2(48, 64),
				"flechitas" : ["→→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(208, 192),
				"titulo": "<#e0483e>Sniper",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Falls with <#238c73>double the normal length." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Eye" :  {
				"tipo" : "especial",
				"chance": 5,  # algo menos común
				"region_rect_cords": Vector2(80, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(48, 192),
				"titulo": "<#e0483e>Eye",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Falls and <#296e8f>adds the score of the domino that contributed the most." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Time Bomb" :  {
				"tipo" : "especial",
				"chance": 4,  # algo menos común
				"region_rect_cords": Vector2(16, 64),
				"flechitas" : ["↖", "↗", "↘", "↙"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 0.5,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 3,
				"plata": "<#b1911a>10",
				"BG": Vector2(48, 192),
				"titulo": "<#238c73>Time <#238c73>Bomb",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Activates after 7 other dominos fell, then explodes." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Mirror" :  {
				"tipo" : "especial",
				"chance": 100,  # algo menos común
				"region_rect_cords": Vector2(112, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(4800, 192),
				"titulo": "<#76357a>Mirror",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Clones the row it is in but only after itself." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Fire" :  {
				"tipo" : "especial",
				"chance": 200,  # algo menos común
				"region_rect_cords": Vector2(144, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 5,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(4800, 192),
				"titulo": "<#f04015>Fire",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "<#f04015>Spreads its effect to all dominos in the chain, giving each <#296e8f>+5 points." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Blue Fire" :  {
				"tipo" : "especial",
				"chance": 1,  # algo menos común
				"region_rect_cords": Vector2(176, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(4800, 192),
				"titulo": "<#407cad>Blue <#407cad>Fire",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Like <#f04015>Fire but <#296e8f>adds one tenth of the affected domino’s score, <#e0483e>multiplied by its position number." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Sticky" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(208, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 5,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(4800, 192),
				"titulo": "<#38b338>Sticky",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "Leaves a <#38b338>”slime <#38b338>trail”, Dominos after it lose their momentum, making the chain slower and adding <#296e8f>+5 points per domino." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Ruler" :  {
				"tipo" : "especial",
				"chance": 3,  # algo menos común
				"region_rect_cords": Vector2(240, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 0,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(4800, 192),
				"titulo": "<#e19124>Ruler",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "<#296e8f>Adds the distance   ( <#e19124>cm ) traveled between each domino from start to finish." # ejemplo: "This domino adds <#f3983a>+1"
			},
	"Stamp Master" :  {
				"tipo" : "especial",
				"chance": 4,  # algo menos común
				"region_rect_cords": Vector2(272, 64),
				"flechitas" : ["→"],
				"stamps": {},
				"mult_actual": 1,
				"mult_global": 1,
				"mult_siguiente": 1,
				"puntaje_siguiente": 0,
				"puntaje": 10,
				"padre" : 0,
				"plata": "<#b1911a>10",
				"BG": Vector2(16, 192),
				"titulo": "<#e0483e>Stamp <#e0483e>Master",  # ejemplo: "1 <#f3983a>Red"
				"descripcion": "The next stamp you <#296e8f>add to this domino will be duplicated, it also <#296e8f>adds <#296e8f>+10." # ejemplo: "This domino adds <#f3983a>+1"
			},
}



func _amuletos():pass
var amuletos = {
	"Rose Ascendant" :    {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#e48b7c>Rose <#296e8f>Ascendant",
						   "descripcion" : "<#296e8f>50% of fallen Rose dominos get a permanent <#296e8f>+1 every time they are used.",
						   },
	"Orange Ascendant" :  {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#f3983a>Orange <#296e8f>Ascendant",
						   "descripcion" : "<#296e8f>50% of fallen Orange dominos get a permanent <#296e8f>+1 every time they are used.",
						   },
	"Blue Ascendant" :    {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#3c4368>Blue <#296e8f>Ascendant",
						   "descripcion" : "<#296e8f>50% of fallen Blue dominos get a permanent <#296e8f>+1 every time they are used.",
						   },
	"Green Ascendant" :   {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#235955>Green <#296e8f>Ascendant",
						   "descripcion" : "<#296e8f>50% of fallen Green dominos get a permanent <#296e8f>+1 every time they are used.",
						   },
	"Rose Flourish" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#e48b7c>Rose <#296e8f>Flourish",
						   "descripcion" : "<#296e8f>50% of fallen Rose dominos get <#e0483e>×1.1 every time they are used.",
						   },
	"Orange Flourish" :   {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#f3983a>Orange <#296e8f>Flourish",
						   "descripcion" : "<#296e8f>50% of fallen Orange dominos get <#e0483e>×1.1 every time they are used.",
						   },
	"Blue Flourish" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#3c4368>Blue <#296e8f>Flourish",
						   "descripcion" : "<#296e8f>50% of fallen Blue dominos get <#e0483e>×1.1 every time they are used.",
						   },
	"Green Flourish" :    {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#235955>Green <#296e8f>Flourish",
						   "descripcion" : "<#296e8f>50% of fallen Green dominos get <#e0483e>×1.1 every time they are used.",
						   },
	"Rose Favor" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#e48b7c>Rose <#296e8f>Favor",
						   "descripcion" : "Chances of Rose dominos to appear are <#e0483e>×1.2 higher.",
						   },
	"Orange Favor" :      {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#f3983a>Orange <#296e8f>Favor",
						   "descripcion" : "Chances of Orange dominos to appear are <#e0483e>×1.2 higher.",
						   },
	"Blue Favor" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#3c4368>Blue <#296e8f>Favor",
						   "descripcion" : "Chances of Blue dominos to appear are <#e0483e>×1.2 higher.",
						   },
	"Green Favor" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#235955>Green <#296e8f>Favor",
						   "descripcion" : "Chances of Green dominos to appear are <#e0483e>×1.2 higher.",
						   },
	"Rose Resurgence" :   {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#e48b7c>Rose <#296e8f>Resurgence",
						   "descripcion" : "The fewer Rose dominos there are, the higher the chance they appear.",
						   },
	"Orange Resurgence" : {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#f3983a>Orange <#296e8f>Resurgence",
						   "descripcion" : "The fewer Orange dominos there are, the higher the chance they appear.",
						   },
	"Blue Resurgence" :   {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#3c4368>Blue <#296e8f>Resurgence",
						   "descripcion" : "The fewer Blue dominos there are, the higher the chance they appear.",
						   },
	"Green Resurgence" :  {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#235955>Green <#296e8f>Resurgence",
						   "descripcion" : "The fewer Green dominos there are, the higher the chance they appear.",
						   },
	"Rose Bloom" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#e48b7c>Rose <#296e8f>Bloom",
						   "descripcion" : "<#296e8f>50% chance for every Rose dominos that scores to <#296e8f>gain <#296e8f>+0.2 color multiplier permanently (max <#e0483e>×2).",
						   },
	"Orange Delight" :    {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#f3983a>Orange <#296e8f>Delight",
						   "descripcion" : "Orange dominos give <#b1911a>2c.",
						   },
	"Domino Surge" :      {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Domino <#296e8f>Surge",
						   "descripcion" : "If a chain contains 5 or more dominos of a single color, that color gets a permanent <#296e8f>+0.5 in it's multiplier.",
						   },
	"Coin Blessing" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Coin <#296e8f>Blessing",
						   "descripcion" : "Gives you <#296e8f>10% extra coins every level cleared.",
						   },
	"Final Wish" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Final <#296e8f>Wish",
						   "descripcion" : "The last play of the level <#296e8f>adds <#e0483e>×.2 to the global multiplier.",
						   },
	"Augmented Chance" :  {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Augmented <#296e8f>Chance",
						   "descripcion" : "Items with chance-based effects get <#e0483e>×1.2 more chances to activate.",
						   },
	"Coin Strike" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Coin <#296e8f>Strike",
						   "descripcion" : "there is a <#296e8f>20% chance for every domino to give you <#b1911a>2c.",
						   },
	"Combo Trinity" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Combo <#296e8f>Trinity",
						   "descripcion" : "If you get 3 or more patterns/combos in a single play, <#296e8f>adds 0.5 to the global multiplier.",
						   },
	"Chain Dealer" :      {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Chain <#296e8f>Dealer",
						   "descripcion" : "Each 7th domino in a chain <#296e8f>adds 0.7 to the global multiplier.",
						   },
	"Lucky Break" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Lucky <#296e8f>Break",
						   "descripcion" : "<#296e8f>10% chance to replay all dominos after a play without any combos.",
						   },
	"Stack Overflow" :    {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Stack <#296e8f>Overflow",
						   "descripcion" : "Every combo type <#296e8f>adds <#296e8f>+5 to the combo's score.",
						   },
	"Greed's Touch" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Greed's <#296e8f>Touch",
						   "descripcion" : "Multiplies all coin rewards from other items by <#e0483e>×1.25.",
						   },
	"Echo Pattern" :      {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Echo <#296e8f>Pattern",
						   "descripcion" : "Repeats the last combo of the play once per level (<#296e8f>50% efficiency).",
						   },
	"Domino Paradox" :    {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Domino <#296e8f>Paradox",
						   "descripcion" : "The first and last domino in a chain both <#296e8f>gain <#296e8f>+10.",
						   },
	"Overgrowth" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Overgrowth",
						   "descripcion" : "If you play 5 or more dominos of the same color, that color <#296e8f>gains <#296e8f>10% spawn chance permanently.",
						   },
	"Fading Luck" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Fading <#296e8f>Luck",
						   "descripcion" : "<#296e8f>Adds <#296e8f>+80 each play, then halves permanently after each use.",
						   },
	"Gold Medal" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Gold <#296e8f>Medal",
						   "descripcion" : "The first combo of every level has <#e0483e>×1.25 power.",
						   },
	"Gold Seed" :         {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Gold <#296e8f>Seed",
						   "descripcion" : "Every <#b1911a>50c owned grants a <#e0483e>×0.5 global multiplier.",
						   },
	"Golden Tree" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Golden <#296e8f>Tree",
						   "descripcion" : "Every <#b1911a>100c owned grants a <#e0483e>×2 global multiplier.",
						   },
	"Trickster's Bloom" : {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Trickster's <#296e8f>Bloom",
						   "descripcion" : "Each time a charm activates, there's a <#296e8f>10% chance for it to activate twice.",
						   },
	"Fifth is the charm" : {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Fifth is the charm",
						   "descripcion" : "Every five charm activations, this repeats the last charm's effect.",
						   },
	"Chain Lock" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Chain <#296e8f>Lock",
						   "descripcion" : "<#296e8f>Gain <#b1911a>+10c if all dominos in a chain have no consecutive colors.",
						   },
	"Domino Spirit" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Domino <#296e8f>Spirit",
						   "descripcion" : "The last domino played in a level permanently <#296e8f>gains <#296e8f>+10 base value.",
						   },
	"Crystal Shard" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Crystal <#296e8f>Shard",
						   "descripcion" : "Each charm activates twice but disables color-based bonuses and combos.",
						   },
	"Puzzle Piece" :      {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Puzzle <#296e8f>Piece",
						   "descripcion" : "If the same combo repeats 3 times in a level, <#296e8f>+3 to the global multiplier.",
						   },
	"Box of Scraps" :     {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Box of <#296e8f>Scraps",
						   "descripcion" : "Let's you have 2 extra charms.",
						   },
	"Sun Pendant" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Sun <#296e8f>Pendant",
						   "descripcion" : "At level start, for every 3 or more same color-type charms owned, <#296e8f>gain <#e0483e>×1.2 global multiplier.",
						   },
	"Amber Core" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Amber <#296e8f>Core",
						   "descripcion" : "When an Orange domino starts a combo, grants <#296e8f>+2 to all other Oranges permanently.",
						   },
	"Sea Shell" :         {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Sea <#296e8f>Shell",
						   "descripcion" : "When a play ends with a Blue domino, <#296e8f>gain <#b1911a>+5c.",
						   },
	"Easy Money" :        {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Easy <#296e8f>Money",
						   "descripcion" : "Get the value of the last domino in coins.",
						   },
	"Rusty Scale" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Rusty <#296e8f>Scale",
						   "descripcion" : "All coins <#296e8f>gained are taxed −<#296e8f>20%, but charm activations are <#e0483e>×1.3 stronger.",
						   },
	"Domino Mask" :       {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Domino <#296e8f>Mask",
						   "descripcion" : "If a chain is only one domino away from a combo, it activates anyway.",
						   },
	"Black Ink" :         {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Black <#296e8f>Ink",
						   "descripcion" : "Missing a color in your deck gives <#296e8f>+2 global multiplier per absent color.",
						   },
	"Crystal Dice" :      {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Crystal <#296e8f>Dice",
						   "descripcion" : "Duplicates one random active charm at the start of a level (temporary).",
						   },
	"Stamper" :           {"size" : Vector2(16,16),
						   "position" : Vector2(0,0),
						   "plata": "<#b1911a>10",
						   "titulo" : "<#296e8f>Stamper",
						   "descripcion" : "Allows you to have up to 3 stamps in a domino.",
						   },
}
